End of sprint commit.
RUGSoftEng/2018-Hippo pull request #32
Opened 2018-05-01 20:33 UTC by JeanMeijer

2018-05-01 20:33 UTC, JeanMeijer commented
In conjunction with pull request from the front end team.

2018-05-03 12:22 UTC, bhichem requested changes
Please process the comments by changing the code, or explaining why changes should not be done before merging.

2018-05-03 12:22 UTC, bhichem commented on Language_tryouts/wordExtract.py
> +def sendToES(tweet):
use snake_case in function naming instead of camelCase

2018-05-03 12:22 UTC, bhichem commented on Language_tryouts/wordExtract.py
> +fdistNames = FreqDist(get_continuous_chunks(inputfile))
use snake_case in variables too 
follow this:
module_name, package_name, ClassName, method_name, ExceptionName, function_name, GLOBAL_CONSTANT_NAME, global_var_name, instance_var_name, function_parameter_name, local_var_name.

2018-05-03 12:22 UTC, bhichem commented on Language_tryouts/wordExtract.py
> +fdistNames.plot(3, cumulative=False)
Better use Classes and functions instead of plain python code

2018-05-11 14:35 UTC, bhichem approved these changes

2018-05-11 14:35 UTC, merged