Merge fix
RUGSoftEng/2018-Hippo pull request #60
Opened 2018-06-04 14:54 UTC by JeanMeijer

2018-06-04 22:32 UTC, bhichem requested changes
Please also edit the readme file and the requirements together with the architecture

2018-06-04 22:32 UTC, bhichem commented on Sources/App/frontend-webpack/src/SearchBar.vue
> +      cmp.endIndex = 10;
what does 10 represents? is it a constant or a variable that could be changed

2018-06-04 22:32 UTC, bhichem commented on Sources/WebApi/hippo_web/api.py
> +def pick_category(terms):
Avoid writing very long functions

2018-06-04 22:32 UTC, bhichem commented on Sources/DataAnalysis/data_analysis/nlp.py
> +def match_keywords_filter(text: str) -> bool:
rewrite this or delete it if it is no longer needed

2018-06-04 22:32 UTC, bhichem commented on Sources/DataAnalysis/runprogram.py
> +content = [
what does this array represent? add comments when things are unclear

2018-06-04 22:32 UTC, bhichem commented on Sources/App/Homepage/js/new-age.js
> +          scrollTop: (target.offset().top - 48)
48 magical number, avoid magical numbers and strings declare them somewhere

2018-06-04 22:32 UTC, bhichem commented on Sources/App/frontend-webpack/src/SearchBar.vue
> +  {
be consist ant about whether or not curly braces are on new line or not

2018-06-08 13:22 UTC, TieSoul commented on Sources/DataAnalysis/data_analysis/nlp.py
> +def match_keywords_filter(text: str) -> bool:
We have removed it in the next version.

2018-06-08 13:25 UTC, TieSoul commented
We will make the requested changes in the next version of Hippo. The current `develop` branch is different enough from this version that we cannot include it in this pull request without drastically changing the content.

2018-06-08 14:35 UTC, merged